### ISSUE TITLE
Error with neural network?

### ISSUE THREAD

**Issue by emily-herbert** [madhavachandra/Machine-Learning-on-Bankruptcy#1]
Hey, 

I am new to R and doing research on bankruptcy prediction. Whenever I try to run 
prob.nnet = predict(bank.nnet, bank.test)
I receive the following mistake: 
Error in model.frame.default(Terms, newdata, na.action = na.omit, xlev = object$xlevels) : 
  factor CUSIP has new levels 00036110, 00078110, 00079X10, 00086T10, 00088630, 00088U10, 00089310, 00089N10, 00095510, 00095710, 00097310, 00100410, 00100T10, 00103110, 00105810, 00108410, 00120410, 00130H10, 00132010, 00143T10, 00154710, 00162710, 00162H10, 00163010, 00163U10, 00167K50, 00171210, 00178510, 00178W10, 00191240, 00193020, 00193710, 00194010, 00202410, 00202J20, 00203R10, 00205830, 00206210, 00206P10, 00206R10, 00207110, 00207R10, 00208310, 00208L10, 00209C10, 00209G20, 00211W10, 00234610, 00245810, 00246W10, 00253994, 00253U10, 00256410, 00256710, 00282410, 00289620, 00292220, 00365410, 00368710, 00370910, 00371F20, 00374N10, 00383010, 00387030, 00388130, 00388N10, 00391010, 00430420, 00430U10, 00431530, 00431910, 00431M30, 00437710, 00437W10, 00440410, 00440P10, 00443E10, 00450D20, 00463110, 00472410, 00481610, 00484810, 00491110, 00493410, 00504X20, 00509L70, 00512510, 00650P30, 00651F10, 00674330, 00675410, 00685420, 00685Q10, 00687R10, 00709410, 00709P10, 007

Does anyone know what the issue is here?

Best, Emily

**Comment by chanmad** [comment]
I found a generic solution that you could leverage. I’m yet to dig into the specific error in this case.

https://stackoverflow.com/questions/22315394/factor-has-new-levels-error-for-variable-im-not-using
